packages:
  home-assistant-zwa-2: !include home-assistant-zwa-2.yaml

esphome:
  project:
    name: esphome.zwa-2-proxy
    version: dev

improv_serial:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/ha-connect-zwa-2/home-assistant-zwa-2/manifest.json

http_request:

dashboard_import:
  package_import_url: github://esphome/zwa-2/home-assistant-zwa-2/home-assistant-zwa-2.yaml@main
