esphome:
  name: home-assistant-zwa-2-poe
  friendly_name: Home Assistant Connect ZWA-2
  min_version: 2025.10.0
  name_add_mac_suffix: true

esp32:
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

ethernet:
  type: W5500
  mosi_pin: GPIO11
  miso_pin: GPIO12
  clk_pin: GPIO13
  cs_pin: GPIO14
  reset_pin: GPIO9
  interrupt_pin: GPIO10

mdns:
  services:
    - service: "_zwave"
      protocol: "_tcp"
      port: 6053
      txt:
        protocol: "esphome"

api:

logger:

ota:
  - platform: esphome
    id: ota_esphome

usb_host:
  devices:
    - id: device_0
      vid: 0x303A
      pid: 0x4001

usb_uart:
  - type: CDC_ACM
    vid: 0x303A
    pid: 0x4001
    channels:
      - id: uch_1
        baud_rate: 115200
        buffer_size: 1024

zwave_proxy:
  id: zw_proxy

button:
  - platform: restart
    id: restart_btn
    name: Restart
    entity_category: diagnostic

  - platform: safe_mode
    id: safe_mode_btn
    name: Safe Mode Boot
    entity_category: diagnostic

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
    entity_category: diagnostic
