name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-wifi-firmware:
    name: Build Wi-Fi Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.8.1
    with:
      files: |
        home-assistant-zwa-2/home-assistant-zwa-2.factory.yaml
      esphome-version: dev
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  build-poe-firmware:
    name: Build PoE Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.8.1
    with:
      files: |
        home-assistant-zwa-2-poe/home-assistant-zwa-2-poe.factory.yaml
      esphome-version: dev
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  upload-to-r2:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    name: Upload to R2
    needs:
      - build-wifi-firmware
      - build-poe-firmware
    uses: esphome/workflows/.github/workflows/upload-to-r2.yml@2025.8.1
    with:
      directory: ha-connect-zwa-2
    secrets: inherit

  upload-to-release:
    name: Upload to Release
    if: github.event_name == 'release'
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.8.1
    needs:
      - build-wifi-firmware
      - build-poe-firmware
    with:
      version: ${{ github.event.release.tag_name }}

  promote-prod:
    name: Promote to Production
    if: github.event_name == 'release' && github.event.release.prerelease == false
    uses: esphome/workflows/.github/workflows/promote-r2.yml@2025.8.1
    needs:
      - upload-to-r2
    with:
      version: ${{ github.event.release.tag_name }}
      directory: ha-connect-zwa-2
      channel: production
      manifest-filename: manifest.json
    secrets: inherit
