name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-wifi-firmware:
    name: Build Wi-Fi Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.8.1
    with:
      files: |
        home-assistant-zwa-2/home-assistant-zwa-2.factory.yaml
      esphome-version: dev
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  get-usb-uart-release:
    name: Get USB/UART Release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch firmware files
        uses: robinraju/release-downloader@v1
        id: download-release
        with:
          repository: NabuCasa/zwave-esp-bridge
          latest: true
          fileName: "*"
          out-file-path: zwave-esp-bridge

      - name: Move files to version folder
        run: |
          version="${{ steps.download-release.outputs.tag_name }}"
          mkdir -p "output/$version"
          mv files/zwave-esp-bridge/* "output/$version/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: output
          name: zwave-esp-bridge

  upload-to-r2:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    name: Upload to R2
    needs:
      - build-wifi-firmware
      - get-usb-uart-release
    uses: esphome/workflows/.github/workflows/upload-to-r2.yml@2025.8.1
    with:
      directory: ha-connect-zwa-2
    secrets: inherit

  upload-to-release:
    name: Upload to Release
    if: github.event_name == 'release'
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.8.1
    needs:
      - build-wifi-firmware
      - get-usb-uart-release
    with:
      version: ${{ github.event.release.tag_name }}

  promote-prod:
    name: Promote to Production
    if: github.event_name == 'release' && github.event.release.prerelease == false
    uses: esphome/workflows/.github/workflows/promote-r2.yml@2025.8.1
    needs:
      - upload-to-r2
    with:
      version: ${{ github.event.release.tag_name }}
      directory: ha-connect-zwa-2
      channel: production
      manifest-filename: manifest.json
    secrets: inherit
